package com.twinkle.common.model;

import com.twinkle.common.model.base.BaseEoltip;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Eoltip extends BaseEoltip<Eoltip> {
	public static final Eoltip dao = new Eoltip().dao();
}
