package com.twinkle.common.model;

import com.twinkle.common.model.base.BaseJwglttb;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Jwglttb extends BaseJwglttb<Jwglttb> {
	public static final Jwglttb dao = new Jwglttb().dao();
}
