package cn.htwinkle.web.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseNetMusic<M extends BaseNetMusic<M>> extends Model<M> implements IBean {

	/**
	 * 主键
	 */
	public M setNetMusicId(java.lang.Integer netMusicId) {
		set("netMusicId", netMusicId);
		return (M)this;
	}
	
	/**
	 * 主键
	 */
	public java.lang.Integer getNetMusicId() {
		return getInt("netMusicId");
	}
	
	/**
	 * 歌曲的id
	 */
	public M setNetMusicSongId(java.lang.String netMusicSongId) {
		set("netMusicSongId", netMusicSongId);
		return (M)this;
	}
	
	/**
	 * 歌曲的id
	 */
	public java.lang.String getNetMusicSongId() {
		return getStr("netMusicSongId");
	}
	
	/**
	 * 歌曲列表的类型（toplist、playlist）
	 */
	public M setNetMusicSongType(java.lang.String netMusicSongType) {
		set("netMusicSongType", netMusicSongType);
		return (M)this;
	}
	
	/**
	 * 歌曲列表的类型（toplist、playlist）
	 */
	public java.lang.String getNetMusicSongType() {
		return getStr("netMusicSongType");
	}
	
	/**
	 * 歌曲列表类型的id
	 */
	public M setNetMusicSongTypeId(java.lang.String netMusicSongTypeId) {
		set("netMusicSongTypeId", netMusicSongTypeId);
		return (M)this;
	}
	
	/**
	 * 歌曲列表类型的id
	 */
	public java.lang.String getNetMusicSongTypeId() {
		return getStr("netMusicSongTypeId");
	}
	
	/**
	 * 歌曲名称
	 */
	public M setNetMusicSongName(java.lang.String netMusicSongName) {
		set("netMusicSongName", netMusicSongName);
		return (M)this;
	}
	
	/**
	 * 歌曲名称
	 */
	public java.lang.String getNetMusicSongName() {
		return getStr("netMusicSongName");
	}
	
	/**
	 * 歌曲演唱者
	 */
	public M setNetMusicSongAuthor(java.lang.String netMusicSongAuthor) {
		set("netMusicSongAuthor", netMusicSongAuthor);
		return (M)this;
	}
	
	/**
	 * 歌曲演唱者
	 */
	public java.lang.String getNetMusicSongAuthor() {
		return getStr("netMusicSongAuthor");
	}
	
	/**
	 * 歌曲时长
	 */
	public M setNetMusicSongTime(java.lang.String netMusicSongTime) {
		set("netMusicSongTime", netMusicSongTime);
		return (M)this;
	}
	
	/**
	 * 歌曲时长
	 */
	public java.lang.String getNetMusicSongTime() {
		return getStr("netMusicSongTime");
	}
	
	/**
	 * 歌曲专辑
	 */
	public M setNetMusicSongAlbum(java.lang.String netMusicSongAlbum) {
		set("netMusicSongAlbum", netMusicSongAlbum);
		return (M)this;
	}
	
	/**
	 * 歌曲专辑
	 */
	public java.lang.String getNetMusicSongAlbum() {
		return getStr("netMusicSongAlbum");
	}
	
	/**
	 * 歌曲mvId
	 */
	public M setNetMusicSongMvId(java.lang.String netMusicSongMvId) {
		set("netMusicSongMvId", netMusicSongMvId);
		return (M)this;
	}
	
	/**
	 * 歌曲mvId
	 */
	public java.lang.String getNetMusicSongMvId() {
		return getStr("netMusicSongMvId");
	}
	
	/**
	 * 抓取时间
	 */
	public M setNetMusicSongDate(java.util.Date netMusicSongDate) {
		set("netMusicSongDate", netMusicSongDate);
		return (M)this;
	}
	
	/**
	 * 抓取时间
	 */
	public java.util.Date getNetMusicSongDate() {
		return getDate("netMusicSongDate");
	}
	
}

