package cn.htwinkle.web.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BasePicture<M extends BasePicture<M>> extends Model<M> implements IBean {

	public M setPictureId(java.lang.Integer pictureId) {
		set("pictureId", pictureId);
		return (M)this;
	}
	
	public java.lang.Integer getPictureId() {
		return getInt("pictureId");
	}

	public M setPictureHost(java.lang.String pictureHost) {
		set("pictureHost", pictureHost);
		return (M)this;
	}
	
	public java.lang.String getPictureHost() {
		return getStr("pictureHost");
	}

	public M setPictureName(java.lang.String pictureName) {
		set("pictureName", pictureName);
		return (M)this;
	}
	
	public java.lang.String getPictureName() {
		return getStr("pictureName");
	}

	public M setPictureTypes(java.lang.String pictureTypes) {
		set("pictureTypes", pictureTypes);
		return (M)this;
	}
	
	public java.lang.String getPictureTypes() {
		return getStr("pictureTypes");
	}

	public M setPictureUrl(java.lang.String pictureUrl) {
		set("pictureUrl", pictureUrl);
		return (M)this;
	}
	
	public java.lang.String getPictureUrl() {
		return getStr("pictureUrl");
	}

	public M setPictureDate(java.util.Date pictureDate) {
		set("pictureDate", pictureDate);
		return (M)this;
	}
	
	public java.util.Date getPictureDate() {
		return get("pictureDate");
	}

}
