package cn.htwinkle.web.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseVisit<M extends BaseVisit<M>> extends Model<M> implements IBean {

	public M setVisitId(java.lang.Integer visitId) {
		set("visitId", visitId);
		return (M)this;
	}
	
	public java.lang.Integer getVisitId() {
		return getInt("visitId");
	}

	public M setVisitIp(java.lang.String visitIp) {
		set("visitIp", visitIp);
		return (M)this;
	}
	
	public java.lang.String getVisitIp() {
		return getStr("visitIp");
	}

	public M setVisitPlace(java.lang.String visitPlace) {
		set("visitPlace", visitPlace);
		return (M)this;
	}
	
	public java.lang.String getVisitPlace() {
		return getStr("visitPlace");
	}

	public M setVisitUserAgent(java.lang.String visitUserAgent) {
		set("visitUserAgent", visitUserAgent);
		return (M)this;
	}
	
	public java.lang.String getVisitUserAgent() {
		return getStr("visitUserAgent");
	}

	public M setVisitDate(java.util.Date visitDate) {
		set("visitDate", visitDate);
		return (M)this;
	}
	
	public java.util.Date getVisitDate() {
		return get("visitDate");
	}

}
