package cn.htwinkle.web.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSmsGroup<M extends BaseSmsGroup<M>> extends Model<M> implements IBean {

	/**
	 * 电话号码
	 */
	public M setSmsTel(java.lang.String smsTel) {
		set("sms_tel", smsTel);
		return (M)this;
	}
	
	/**
	 * 电话号码
	 */
	public java.lang.String getSmsTel() {
		return getStr("sms_tel");
	}
	
	/**
	 * 名字
	 */
	public M setSmsName(java.lang.String smsName) {
		set("sms_name", smsName);
		return (M)this;
	}
	
	/**
	 * 名字
	 */
	public java.lang.String getSmsName() {
		return getStr("sms_name");
	}
	
	/**
	 * 发送的名字
	 */
	public M setSmsSendName(java.lang.String smsSendName) {
		set("sms_send_name", smsSendName);
		return (M)this;
	}
	
	/**
	 * 发送的名字
	 */
	public java.lang.String getSmsSendName() {
		return getStr("sms_send_name");
	}
	
	/**
	 * 设备的唯一标志
	 */
	public M setTelSn(java.lang.String telSn) {
		set("tel_sn", telSn);
		return (M)this;
	}
	
	/**
	 * 设备的唯一标志
	 */
	public java.lang.String getTelSn() {
		return getStr("tel_sn");
	}
	
	/**
	 * 备份的标志
	 */
	public M setSmsBackup(java.lang.Integer smsBackup) {
		set("sms_backup", smsBackup);
		return (M)this;
	}
	
	/**
	 * 备份的标志
	 */
	public java.lang.Integer getSmsBackup() {
		return getInt("sms_backup");
	}
	
	/**
	 * 发送的标志
	 */
	public M setSmsSendStatus(java.lang.Integer smsSendStatus) {
		set("sms_send_status", smsSendStatus);
		return (M)this;
	}
	
	/**
	 * 发送的标志
	 */
	public java.lang.Integer getSmsSendStatus() {
		return getInt("sms_send_status");
	}
	
}

