package cn.htwinkle.web.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseNetMusicPlayList<M extends BaseNetMusicPlayList<M>> extends Model<M> implements IBean {

	/**
	 * 网易云音乐歌单列表id
	 */
	public M setNetMusicPlayListId(java.lang.Integer netMusicPlayListId) {
		set("netMusicPlayListId", netMusicPlayListId);
		return (M)this;
	}
	
	/**
	 * 网易云音乐歌单列表id
	 */
	public java.lang.Integer getNetMusicPlayListId() {
		return getInt("netMusicPlayListId");
	}
	
	/**
	 * 歌单列表网页id
	 */
	public M setNetMusicPlayListDirId(java.lang.String netMusicPlayListDirId) {
		set("netMusicPlayListDirId", netMusicPlayListDirId);
		return (M)this;
	}
	
	/**
	 * 歌单列表网页id
	 */
	public java.lang.String getNetMusicPlayListDirId() {
		return getStr("netMusicPlayListDirId");
	}
	
	/**
	 * 歌单列表网页名字
	 */
	public M setNetMusicPlayListName(java.lang.String netMusicPlayListName) {
		set("netMusicPlayListName", netMusicPlayListName);
		return (M)this;
	}
	
	/**
	 * 歌单列表网页名字
	 */
	public java.lang.String getNetMusicPlayListName() {
		return getStr("netMusicPlayListName");
	}
	
	/**
	 * 歌单列表类型（toplist、playlist）
	 */
	public M setNetMusicPlayListType(java.lang.String netMusicPlayListType) {
		set("netMusicPlayListType", netMusicPlayListType);
		return (M)this;
	}
	
	/**
	 * 歌单列表类型（toplist、playlist）
	 */
	public java.lang.String getNetMusicPlayListType() {
		return getStr("netMusicPlayListType");
	}
	
	/**
	 * 歌单列表最新更新时间
	 */
	public M setNetMusicPlayListUpdate(java.lang.String netMusicPlayListUpdate) {
		set("netMusicPlayListUpdate", netMusicPlayListUpdate);
		return (M)this;
	}
	
	/**
	 * 歌单列表最新更新时间
	 */
	public java.lang.String getNetMusicPlayListUpdate() {
		return getStr("netMusicPlayListUpdate");
	}
	
	/**
	 * 歌单列表播放次数
	 */
	public M setNetMusicPlayListCount(java.lang.String netMusicPlayListCount) {
		set("netMusicPlayListCount", netMusicPlayListCount);
		return (M)this;
	}
	
	/**
	 * 歌单列表播放次数
	 */
	public java.lang.String getNetMusicPlayListCount() {
		return getStr("netMusicPlayListCount");
	}
	
	/**
	 * 歌单列表抓取时间
	 */
	public M setNetMusicPlayListDate(java.time.LocalDateTime netMusicPlayListDate) {
		set("netMusicPlayListDate", netMusicPlayListDate);
		return (M)this;
	}
	
	/**
	 * 歌单列表抓取时间
	 */
	public java.time.LocalDateTime getNetMusicPlayListDate() {
		return getLocalDateTime("netMusicPlayListDate");
	}
	
}

