package com.jfinal.common.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("eol", "id", Eol.class);
		arp.addMapping("eoltip", "id", Eoltip.class);
		arp.addMapping("globalcount", "id", Globalcount.class);
		arp.addMapping("img", "id", Img.class);
		arp.addMapping("jwgl", "id", Jwgl.class);
		arp.addMapping("jwglinfo", "id", Jwglinfo.class);
		arp.addMapping("jwglscore", "id", Jwglscore.class);
		arp.addMapping("jwglttb", "id", Jwglttb.class);
		arp.addMapping("article", "id", Article.class);
		arp.addMapping("netmusic", "id", Netmusic.class);
	}
}

