package com.jfinal.common.model;

import com.jfinal.common.model.base.BaseGlobalcount;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Globalcount extends BaseGlobalcount<Globalcount> {
	public static final Globalcount dao = new Globalcount().dao();
}
