package com.jfinal.common.model;

import com.jfinal.common.model.base.BaseImg;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Img extends BaseImg<Img> {
	public static final Img dao = new Img().dao();
}
