package com.jfinal.common.model;

import java.util.List;

import com.jfinal.common.model.base.BaseJwgl;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Jwgl extends BaseJwgl<Jwgl> {
	
	public static final Jwgl dao = new Jwgl().dao();
	
	private Jwglinfo jwglinfo;
	private Jwglttb jwglttb;
	private List<Jwglscore> jwglscore;


	public Jwglinfo getJwglinfo() {
		return jwglinfo;
	}

	public void setJwglinfo(Jwglinfo jwglinfo) {
		this.jwglinfo = jwglinfo;
	}

	public static Jwgl getDao() {
		return dao;
	}

	public Jwglttb getJwglttb() {
		return jwglttb;
	}

	public void setJwglttb(Jwglttb jwglttb) {
		this.jwglttb = jwglttb;
	}

	public List<Jwglscore> getJwglscore() {
		return jwglscore;
	}

	public void setJwglscore(List<Jwglscore> jwglscore) {
		this.jwglscore = jwglscore;
	}

	
	
	
}
