package com.jfinal.common.model;

import com.jfinal.common.model.base.BaseJwglinfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Jwglinfo extends BaseJwglinfo<Jwglinfo> {
	public static final Jwglinfo dao = new Jwglinfo().dao();
}
