package com.jfinal.common.model;

import com.jfinal.common.model.base.BaseNetmusic;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Netmusic extends BaseNetmusic<Netmusic> {
	public static final Netmusic dao = new Netmusic().dao();
}
