package com.twinkle.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseJwglinfo<M extends BaseJwglinfo<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setUserid(java.lang.Integer userid) {
		set("userid", userid);
		return (M)this;
	}
	
	public java.lang.Integer getUserid() {
		return getInt("userid");
	}

	public M setXh(java.lang.String xh) {
		set("xh", xh);
		return (M)this;
	}
	
	public java.lang.String getXh() {
		return getStr("xh");
	}

	public M setXm(java.lang.String xm) {
		set("xm", xm);
		return (M)this;
	}
	
	public java.lang.String getXm() {
		return getStr("xm");
	}

	public M setXszp(java.lang.String xszp) {
		set("xszp", xszp);
		return (M)this;
	}
	
	public java.lang.String getXszp() {
		return getStr("xszp");
	}

	public M setLblXb(java.lang.String lblXb) {
		set("lbl_xb", lblXb);
		return (M)this;
	}
	
	public java.lang.String getLblXb() {
		return getStr("lbl_xb");
	}

	public M setLblRxrq(java.lang.String lblRxrq) {
		set("lbl_rxrq", lblRxrq);
		return (M)this;
	}
	
	public java.lang.String getLblRxrq() {
		return getStr("lbl_rxrq");
	}

	public M setLblCsrq(java.lang.String lblCsrq) {
		set("lbl_csrq", lblCsrq);
		return (M)this;
	}
	
	public java.lang.String getLblCsrq() {
		return getStr("lbl_csrq");
	}

	public M setLblMz(java.lang.String lblMz) {
		set("lbl_mz", lblMz);
		return (M)this;
	}
	
	public java.lang.String getLblMz() {
		return getStr("lbl_mz");
	}

	public M setLblZzmm(java.lang.String lblZzmm) {
		set("lbl_zzmm", lblZzmm);
		return (M)this;
	}
	
	public java.lang.String getLblZzmm() {
		return getStr("lbl_zzmm");
	}

	public M setLblLxdh(java.lang.String lblLxdh) {
		set("lbl_lxdh", lblLxdh);
		return (M)this;
	}
	
	public java.lang.String getLblLxdh() {
		return getStr("lbl_lxdh");
	}

	public M setLblYzbm(java.lang.String lblYzbm) {
		set("lbl_yzbm", lblYzbm);
		return (M)this;
	}
	
	public java.lang.String getLblYzbm() {
		return getStr("lbl_yzbm");
	}

	public M setLblZkzh(java.lang.String lblZkzh) {
		set("lbl_zkzh", lblZkzh);
		return (M)this;
	}
	
	public java.lang.String getLblZkzh() {
		return getStr("lbl_zkzh");
	}

	public M setLblSfzh(java.lang.String lblSfzh) {
		set("lbl_sfzh", lblSfzh);
		return (M)this;
	}
	
	public java.lang.String getLblSfzh() {
		return getStr("lbl_sfzh");
	}

	public M setLblCc(java.lang.String lblCc) {
		set("lbl_CC", lblCc);
		return (M)this;
	}
	
	public java.lang.String getLblCc() {
		return getStr("lbl_CC");
	}

	public M setLblXy(java.lang.String lblXy) {
		set("lbl_xy", lblXy);
		return (M)this;
	}
	
	public java.lang.String getLblXy() {
		return getStr("lbl_xy");
	}

	public M setLblJtszd(java.lang.String lblJtszd) {
		set("lbl_jtszd", lblJtszd);
		return (M)this;
	}
	
	public java.lang.String getLblJtszd() {
		return getStr("lbl_jtszd");
	}

	public M setLblZymc(java.lang.String lblZymc) {
		set("lbl_zymc", lblZymc);
		return (M)this;
	}
	
	public java.lang.String getLblZymc() {
		return getStr("lbl_zymc");
	}

	public M setLblXzb(java.lang.String lblXzb) {
		set("lbl_xzb", lblXzb);
		return (M)this;
	}
	
	public java.lang.String getLblXzb() {
		return getStr("lbl_xzb");
	}

	public M setLblYycj(java.lang.String lblYycj) {
		set("lbl_YYCJ", lblYycj);
		return (M)this;
	}
	
	public java.lang.String getLblYycj() {
		return getStr("lbl_YYCJ");
	}

	public M setLblXz(java.lang.String lblXz) {
		set("lbl_xz", lblXz);
		return (M)this;
	}
	
	public java.lang.String getLblXz() {
		return getStr("lbl_xz");
	}

	public M setLblXjzt(java.lang.String lblXjzt) {
		set("lbl_xjzt", lblXjzt);
		return (M)this;
	}
	
	public java.lang.String getLblXjzt() {
		return getStr("lbl_xjzt");
	}

	public M setLblDqszj(java.lang.String lblDqszj) {
		set("lbl_dqszj", lblDqszj);
		return (M)this;
	}
	
	public java.lang.String getLblDqszj() {
		return getStr("lbl_dqszj");
	}

	public M setLblKsh(java.lang.String lblKsh) {
		set("lbl_ksh", lblKsh);
		return (M)this;
	}
	
	public java.lang.String getLblKsh() {
		return getStr("lbl_ksh");
	}

	public M setDates(java.util.Date dates) {
		set("dates", dates);
		return (M)this;
	}
	
	public java.util.Date getDates() {
		return get("dates");
	}

}
