package com.twinkle.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseJwglscore<M extends BaseJwglscore<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setUserid(java.lang.Integer userid) {
		set("userid", userid);
		return (M)this;
	}
	
	public java.lang.Integer getUserid() {
		return getInt("userid");
	}

	public M setXuenian(java.lang.String xuenian) {
		set("xuenian", xuenian);
		return (M)this;
	}
	
	public java.lang.String getXuenian() {
		return getStr("xuenian");
	}

	public M setXueqi(java.lang.String xueqi) {
		set("xueqi", xueqi);
		return (M)this;
	}
	
	public java.lang.String getXueqi() {
		return getStr("xueqi");
	}

	public M setKechengdaima(java.lang.String kechengdaima) {
		set("kechengdaima", kechengdaima);
		return (M)this;
	}
	
	public java.lang.String getKechengdaima() {
		return getStr("kechengdaima");
	}

	public M setKechengmingcheng(java.lang.String kechengmingcheng) {
		set("kechengmingcheng", kechengmingcheng);
		return (M)this;
	}
	
	public java.lang.String getKechengmingcheng() {
		return getStr("kechengmingcheng");
	}

	public M setKechengxingzhi(java.lang.String kechengxingzhi) {
		set("kechengxingzhi", kechengxingzhi);
		return (M)this;
	}
	
	public java.lang.String getKechengxingzhi() {
		return getStr("kechengxingzhi");
	}

	public M setKechengguishu(java.lang.String kechengguishu) {
		set("kechengguishu", kechengguishu);
		return (M)this;
	}
	
	public java.lang.String getKechengguishu() {
		return getStr("kechengguishu");
	}

	public M setXuefen(java.lang.String xuefen) {
		set("xuefen", xuefen);
		return (M)this;
	}
	
	public java.lang.String getXuefen() {
		return getStr("xuefen");
	}

	public M setJidian(java.lang.String jidian) {
		set("jidian", jidian);
		return (M)this;
	}
	
	public java.lang.String getJidian() {
		return getStr("jidian");
	}

	public M setChengji(java.lang.String chengji) {
		set("chengji", chengji);
		return (M)this;
	}
	
	public java.lang.String getChengji() {
		return getStr("chengji");
	}

	public M setFuxiubiaoji(java.lang.String fuxiubiaoji) {
		set("fuxiubiaoji", fuxiubiaoji);
		return (M)this;
	}
	
	public java.lang.String getFuxiubiaoji() {
		return getStr("fuxiubiaoji");
	}

	public M setBukaochengji(java.lang.String bukaochengji) {
		set("bukaochengji", bukaochengji);
		return (M)this;
	}
	
	public java.lang.String getBukaochengji() {
		return getStr("bukaochengji");
	}

	public M setChongxiuchengji(java.lang.String chongxiuchengji) {
		set("chongxiuchengji", chongxiuchengji);
		return (M)this;
	}
	
	public java.lang.String getChongxiuchengji() {
		return getStr("chongxiuchengji");
	}

	public M setXueyuanmingchen(java.lang.String xueyuanmingchen) {
		set("xueyuanmingchen", xueyuanmingchen);
		return (M)this;
	}
	
	public java.lang.String getXueyuanmingchen() {
		return getStr("xueyuanmingchen");
	}

	public M setChongxiubiaoji(java.lang.String chongxiubiaoji) {
		set("chongxiubiaoji", chongxiubiaoji);
		return (M)this;
	}
	
	public java.lang.String getChongxiubiaoji() {
		return getStr("chongxiubiaoji");
	}

	public M setDates(java.util.Date dates) {
		set("dates", dates);
		return (M)this;
	}
	
	public java.util.Date getDates() {
		return get("dates");
	}

}
