package com.twinkle.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BasePost<M extends BasePost<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setTitle(java.lang.String title) {
		set("title", title);
		return (M)this;
	}
	
	public java.lang.String getTitle() {
		return getStr("title");
	}

	public M setAuthor(java.lang.String author) {
		set("author", author);
		return (M)this;
	}
	
	public java.lang.String getAuthor() {
		return getStr("author");
	}

	public M setContent(java.lang.String content) {
		set("content", content);
		return (M)this;
	}
	
	public java.lang.String getContent() {
		return getStr("content");
	}

	public M setPic(java.lang.String pic) {
		set("pic", pic);
		return (M)this;
	}
	
	public java.lang.String getPic() {
		return getStr("pic");
	}

	public M setTopic(java.lang.String topic) {
		set("topic", topic);
		return (M)this;
	}
	
	public java.lang.String getTopic() {
		return getStr("topic");
	}

	public M setPlace(java.lang.String place) {
		set("place", place);
		return (M)this;
	}
	
	public java.lang.String getPlace() {
		return getStr("place");
	}

	public M setUrl(java.lang.String url) {
		set("url", url);
		return (M)this;
	}
	
	public java.lang.String getUrl() {
		return getStr("url");
	}

	public M setHot(java.lang.String hot) {
		set("hot", hot);
		return (M)this;
	}
	
	public java.lang.String getHot() {
		return getStr("hot");
	}

	public M setTypes(java.lang.String types) {
		set("types", types);
		return (M)this;
	}
	
	public java.lang.String getTypes() {
		return getStr("types");
	}

	public M setNewsdate(java.lang.String newsdate) {
		set("newsdate", newsdate);
		return (M)this;
	}
	
	public java.lang.String getNewsdate() {
		return getStr("newsdate");
	}

	public M setDates(java.util.Date dates) {
		set("dates", dates);
		return (M)this;
	}
	
	public java.util.Date getDates() {
		return get("dates");
	}

}
