package com.twinkle.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseJwglscore<M extends BaseJwglscore<M>> extends Model<M> implements IBean {

	public M setId(Integer id) {
		set("id", id);
		return (M)this;
	}

	public Integer getId() {
		return getInt("id");
	}

	public M setUserid(Integer userid) {
		set("userid", userid);
		return (M)this;
	}

	public Integer getUserid() {
		return getInt("userid");
	}

	public M setXuenian(String xuenian) {
		set("xuenian", xuenian);
		return (M)this;
	}

	public String getXuenian() {
		return getStr("xuenian");
	}

	public M setXueqi(String xueqi) {
		set("xueqi", xueqi);
		return (M)this;
	}

	public String getXueqi() {
		return getStr("xueqi");
	}

	public M setKechengdaima(String kechengdaima) {
		set("kechengdaima", kechengdaima);
		return (M)this;
	}

	public String getKechengdaima() {
		return getStr("kechengdaima");
	}

	public M setKechengmingcheng(String kechengmingcheng) {
		set("kechengmingcheng", kechengmingcheng);
		return (M)this;
	}

	public String getKechengmingcheng() {
		return getStr("kechengmingcheng");
	}

	public M setKechengxingzhi(String kechengxingzhi) {
		set("kechengxingzhi", kechengxingzhi);
		return (M)this;
	}

	public String getKechengxingzhi() {
		return getStr("kechengxingzhi");
	}

	public M setKechengguishu(String kechengguishu) {
		set("kechengguishu", kechengguishu);
		return (M)this;
	}

	public String getKechengguishu() {
		return getStr("kechengguishu");
	}

	public M setXuefen(String xuefen) {
		set("xuefen", xuefen);
		return (M)this;
	}

	public String getXuefen() {
		return getStr("xuefen");
	}

	public M setJidian(String jidian) {
		set("jidian", jidian);
		return (M)this;
	}

	public String getJidian() {
		return getStr("jidian");
	}

	public M setChengji(String chengji) {
		set("chengji", chengji);
		return (M)this;
	}

	public String getChengji() {
		return getStr("chengji");
	}

	public M setFuxiubiaoji(String fuxiubiaoji) {
		set("fuxiubiaoji", fuxiubiaoji);
		return (M)this;
	}

	public String getFuxiubiaoji() {
		return getStr("fuxiubiaoji");
	}

	public M setBukaochengji(String bukaochengji) {
		set("bukaochengji", bukaochengji);
		return (M)this;
	}

	public String getBukaochengji() {
		return getStr("bukaochengji");
	}

	public M setChongxiuchengji(String chongxiuchengji) {
		set("chongxiuchengji", chongxiuchengji);
		return (M)this;
	}

	public String getChongxiuchengji() {
		return getStr("chongxiuchengji");
	}

	public M setXueyuanmingchen(String xueyuanmingchen) {
		set("xueyuanmingchen", xueyuanmingchen);
		return (M)this;
	}

	public String getXueyuanmingchen() {
		return getStr("xueyuanmingchen");
	}

	public M setChongxiubiaoji(String chongxiubiaoji) {
		set("chongxiubiaoji", chongxiubiaoji);
		return (M)this;
	}

	public String getChongxiubiaoji() {
		return getStr("chongxiubiaoji");
	}

	public M setDates(java.util.Date dates) {
		set("dates", dates);
		return (M)this;
	}
	
	public java.util.Date getDates() {
		return get("dates");
	}

}
