package com.twinkle.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseJwglinfo<M extends BaseJwglinfo<M>> extends Model<M> implements IBean {

	public M setId(Integer id) {
		set("id", id);
		return (M)this;
	}

	public Integer getId() {
		return getInt("id");
	}

	public M setUserid(Integer userid) {
		set("userid", userid);
		return (M)this;
	}

	public Integer getUserid() {
		return getInt("userid");
	}

	public M setXh(String xh) {
		set("xh", xh);
		return (M)this;
	}

	public String getXh() {
		return getStr("xh");
	}

	public M setXm(String xm) {
		set("xm", xm);
		return (M)this;
	}

	public String getXm() {
		return getStr("xm");
	}

	public M setXszp(String xszp) {
		set("xszp", xszp);
		return (M)this;
	}

	public String getXszp() {
		return getStr("xszp");
	}

	public M setLblXb(String lblXb) {
		set("lbl_xb", lblXb);
		return (M)this;
	}

	public String getLblXb() {
		return getStr("lbl_xb");
	}

	public M setLblRxrq(String lblRxrq) {
		set("lbl_rxrq", lblRxrq);
		return (M)this;
	}

	public String getLblRxrq() {
		return getStr("lbl_rxrq");
	}

	public M setLblCsrq(String lblCsrq) {
		set("lbl_csrq", lblCsrq);
		return (M)this;
	}

	public String getLblCsrq() {
		return getStr("lbl_csrq");
	}

	public M setLblMz(String lblMz) {
		set("lbl_mz", lblMz);
		return (M)this;
	}

	public String getLblMz() {
		return getStr("lbl_mz");
	}

	public M setLblZzmm(String lblZzmm) {
		set("lbl_zzmm", lblZzmm);
		return (M)this;
	}

	public String getLblZzmm() {
		return getStr("lbl_zzmm");
	}

	public M setLblLxdh(String lblLxdh) {
		set("lbl_lxdh", lblLxdh);
		return (M)this;
	}

	public String getLblLxdh() {
		return getStr("lbl_lxdh");
	}

	public M setLblYzbm(String lblYzbm) {
		set("lbl_yzbm", lblYzbm);
		return (M)this;
	}

	public String getLblYzbm() {
		return getStr("lbl_yzbm");
	}

	public M setLblZkzh(String lblZkzh) {
		set("lbl_zkzh", lblZkzh);
		return (M)this;
	}

	public String getLblZkzh() {
		return getStr("lbl_zkzh");
	}

	public M setLblSfzh(String lblSfzh) {
		set("lbl_sfzh", lblSfzh);
		return (M)this;
	}

	public String getLblSfzh() {
		return getStr("lbl_sfzh");
	}

	public M setLblCc(String lblCc) {
		set("lbl_CC", lblCc);
		return (M)this;
	}

	public String getLblCc() {
		return getStr("lbl_CC");
	}

	public M setLblXy(String lblXy) {
		set("lbl_xy", lblXy);
		return (M)this;
	}

	public String getLblXy() {
		return getStr("lbl_xy");
	}

	public M setLblJtszd(String lblJtszd) {
		set("lbl_jtszd", lblJtszd);
		return (M)this;
	}

	public String getLblJtszd() {
		return getStr("lbl_jtszd");
	}

	public M setLblZymc(String lblZymc) {
		set("lbl_zymc", lblZymc);
		return (M)this;
	}

	public String getLblZymc() {
		return getStr("lbl_zymc");
	}

	public M setLblXzb(String lblXzb) {
		set("lbl_xzb", lblXzb);
		return (M)this;
	}

	public String getLblXzb() {
		return getStr("lbl_xzb");
	}

	public M setLblYycj(String lblYycj) {
		set("lbl_YYCJ", lblYycj);
		return (M)this;
	}

	public String getLblYycj() {
		return getStr("lbl_YYCJ");
	}

	public M setLblXz(String lblXz) {
		set("lbl_xz", lblXz);
		return (M)this;
	}

	public String getLblXz() {
		return getStr("lbl_xz");
	}

	public M setLblXjzt(String lblXjzt) {
		set("lbl_xjzt", lblXjzt);
		return (M)this;
	}

	public String getLblXjzt() {
		return getStr("lbl_xjzt");
	}

	public M setLblDqszj(String lblDqszj) {
		set("lbl_dqszj", lblDqszj);
		return (M)this;
	}

	public String getLblDqszj() {
		return getStr("lbl_dqszj");
	}

	public M setLblKsh(String lblKsh) {
		set("lbl_ksh", lblKsh);
		return (M)this;
	}

	public String getLblKsh() {
		return getStr("lbl_ksh");
	}

	public M setDates(java.util.Date dates) {
		set("dates", dates);
		return (M)this;
	}
	
	public java.util.Date getDates() {
		return get("dates");
	}

}
