package com.twinkle.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseImg<M extends BaseImg<M>> extends Model<M> implements IBean {

	public M setId(Integer id) {
		set("id", id);
		return (M)this;
	}

	public Integer getId() {
		return getInt("id");
	}

	public M setHost(String host) {
		set("host", host);
		return (M)this;
	}

	public String getHost() {
		return getStr("host");
	}

	public M setName(String name) {
		set("name", name);
		return (M)this;
	}

	public String getName() {
		return getStr("name");
	}

	public M setTypes(String types) {
		set("types", types);
		return (M)this;
	}

	public String getTypes() {
		return getStr("types");
	}

	public M setPic(String pic) {
		set("pic", pic);
		return (M)this;
	}

	public String getPic() {
		return getStr("pic");
	}

	public M setDate(java.util.Date date) {
		set("date", date);
		return (M)this;
	}
	
	public java.util.Date getDate() {
		return get("date");
	}

}
