package com.twinkle.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseGlobalcount<M extends BaseGlobalcount<M>> extends Model<M> implements IBean {

	public M setId(Integer id) {
		set("id", id);
		return (M)this;
	}

	public Integer getId() {
		return getInt("id");
	}

	public M setIp(String ip) {
		set("ip", ip);
		return (M)this;
	}

	public String getIp() {
		return getStr("ip");
	}

	public M setPlace(String place) {
		set("place", place);
		return (M)this;
	}

	public String getPlace() {
		return getStr("place");
	}

	public M setNum(Integer num) {
		set("num", num);
		return (M)this;
	}

	public Integer getNum() {
		return getInt("num");
	}

	public M setDates(java.util.Date dates) {
		set("dates", dates);
		return (M)this;
	}
	
	public java.util.Date getDates() {
		return get("dates");
	}

}
