package com.twinkle.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseEol<M extends BaseEol<M>> extends Model<M> implements IBean {

	public M setId(Integer id) {
		set("id", id);
		return (M)this;
	}

	public Integer getId() {
		return getInt("id");
	}

	public M setCode(Integer code) {
		set("code", code);
		return (M)this;
	}

	public Integer getCode() {
		return getInt("code");
	}

	public M setAdmin(String admin) {
		set("admin", admin);
		return (M)this;
	}

	public String getAdmin() {
		return getStr("admin");
	}

	public M setPass(String pass) {
		set("pass", pass);
		return (M)this;
	}

	public String getPass() {
		return getStr("pass");
	}

	public M setName(String name) {
		set("name", name);
		return (M)this;
	}

	public String getName() {
		return getStr("name");
	}

	public M setCookies(String cookies) {
		set("cookies", cookies);
		return (M)this;
	}

	public String getCookies() {
		return getStr("cookies");
	}

	public M setTip(String tip) {
		set("tip", tip);
		return (M)this;
	}

	public String getTip() {
		return getStr("tip");
	}

	public M setLoginfre(String loginfre) {
		set("loginfre", loginfre);
		return (M)this;
	}

	public String getLoginfre() {
		return getStr("loginfre");
	}

	public M setOnlinetime(String onlinetime) {
		set("onlinetime", onlinetime);
		return (M)this;
	}

	public String getOnlinetime() {
		return getStr("onlinetime");
	}

	public M setDates(java.util.Date dates) {
		set("dates", dates);
		return (M)this;
	}
	
	public java.util.Date getDates() {
		return get("dates");
	}

}
