package com.jfinal.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseJwgl<M extends BaseJwgl<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setCode(java.lang.Integer code) {
		set("code", code);
		return (M)this;
	}
	
	public java.lang.Integer getCode() {
		return getInt("code");
	}

	public M setAdmin(java.lang.String admin) {
		set("admin", admin);
		return (M)this;
	}
	
	public java.lang.String getAdmin() {
		return getStr("admin");
	}

	public M setPass(java.lang.String pass) {
		set("pass", pass);
		return (M)this;
	}
	
	public java.lang.String getPass() {
		return getStr("pass");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public M setCookies(java.lang.String cookies) {
		set("cookies", cookies);
		return (M)this;
	}
	
	public java.lang.String getCookies() {
		return getStr("cookies");
	}

	public M setTip(java.lang.String tip) {
		set("tip", tip);
		return (M)this;
	}
	
	public java.lang.String getTip() {
		return getStr("tip");
	}

	public M setDates(java.util.Date dates) {
		set("dates", dates);
		return (M)this;
	}
	
	public java.util.Date getDates() {
		return get("dates");
	}

}
