package com.twinkle.common.model;

import com.twinkle.common.model.base.BaseJwglscore;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Jwglscore extends BaseJwglscore<Jwglscore> {
	public static final Jwglscore dao = new Jwglscore().dao();
}
