package cn.htwinkle.devotion.model;

import cn.htwinkle.devotion.model.base.BasePicture;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Picture extends BasePicture<Picture> {
	public static final Picture dao = new Picture().dao();
}
