package cn.htwinkle.devotion.model;

import cn.htwinkle.devotion.model.base.BaseVisit;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Visit extends BaseVisit<Visit> {
	public static final Visit dao = new Visit().dao();
}
