package cn.htwinkle.web.model;

import cn.htwinkle.web.model.base.BaseNetMusicPlayList;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class NetMusicPlayList extends BaseNetMusicPlayList<NetMusicPlayList> {
	public static final NetMusicPlayList dao = new NetMusicPlayList().dao();
}
