package cn.htwinkle.web.model;

import cn.htwinkle.web.model.base.BaseNetMusic;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class NetMusic extends BaseNetMusic<NetMusic> {
	public static final NetMusic dao = new NetMusic().dao();
}
