package cn.htwinkle.web.model;

import cn.htwinkle.web.model.base.BaseSmsGroup;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SmsGroup extends BaseSmsGroup<SmsGroup> {
	public static final SmsGroup dao = new SmsGroup().dao();
}

